### PR TITLE
Fixed Clicked item with on readonly

### PR DESCRIPTION
**Pull request by xxAROX**
Fixed Clicked item with on readonly

### CODE REVIEW

**Comment by Muqsit** [comment]
Can you describe what the issue is and how is it being fixed?

**Comment by xxAROX** [comment]
before if i clicked on readonly without an item in my curser inventory the item in chest was picked up into my curser inventory

**Comment by xxAROX** [comment]
how i fixed it => i cleand the curser inventory

**Review by callumrawlinson — COMMENTED** [review]
looks good

**Review by callumrawlinson — APPROVED** [review]
approved by me!

**Comment by callumrawlinson** [comment]
tested it and it works really good!

**Comment by Muqsit** [comment]
@xxAROX I understand the bug, however I don't think this is a suitable fix for the issue due to the assumption that a player's cursor inventory is not modified during a cancelled transaction, which potentially leads to an inventory rollback being performed.

Ideally, InvMenu's job during an inventory transaction is to only get a response from the listener on whether to cancel the transaction or not. Anything more (such as setting an item in inventory) is tampering with the behaviour of the listener.

**Comment by xxAROX** [comment]
i understand

**Comment by xxAROX** [comment]
grafik

**Comment by xxAROX** [comment]
i tested it much times with no rollback result

**Comment by callumrawlinson** [comment]
:)

**Comment by xxAROX** [comment]
> player's cursor inventory is not modified during a cancelled transaction
Display error fix

**Comment by xxAROX** [comment]
[player won't lose items](https://github.com/xxAROX/InvMenu/blob/patch-1/src/muqsit/invmenu/InvMenu.php#L53)

**Comment by Muqsit** [comment]
@xxAROX Can you test if this bug occurs without InvMenu? Cancel InventoryTransactionEvent through a plugin and try placing an item in a chest.

**Comment by xxAROX** [comment]
wait i look

**Comment by xxAROX** [comment]
Current InvMenu(not my PR), its:
 - Create readonly listener
 - You Pick any item
 - Trancaction will cancelled
 - Item is still in your curser inventory

**Comment by Muqsit** [comment]
@xxAROX Yeah, I understand your approach in fixing this issue. I'd like to know if this bug occurs outside of InvMenu (i.e., it's a bug within the core).
I would appreciate it if you could test if this bug occurs if you placed a chest on ground, opened it and moved an item from it while having a plugin cancel InventoryTransactionEvent.

**Comment by xxAROX** [comment]
yea my game is starting

**Comment by xxAROX** [comment]
works readonly

**Comment by xxAROX** [comment]
no, sometimes it works

**Comment by xxAROX** [comment]
```php
	public function event(InventoryTransactionEvent $event): void{
		$transaction = $event->getTransaction();
		foreach ($transaction->getInventories() as $inventory) {
			if ($inventory instanceof ChestInventory) {
				$event->setCancelled(true);
				foreach ($transaction->getActions() as $action) {
					if ($action->getTargetItem()->getId() != 0) {
						$transaction->getSource()->getCursorInventory()->setItem(0, $action->getTargetItem());
					} else {
						$transaction->getSource()->getCursorInventory()->setItem(0, Item::get(0));
					}
				}
			}
		}
	}
```

**Comment by xxAROX** [comment]
i test only setCancelled

**Comment by xxAROX** [comment]
> 
> 
> i test only setCancelled

nothing happend

**Comment by xxAROX** [comment]
here is my PR version ( sorry for bg-music :/ )

https://user-images.githubusercontent.com/57589973/109646610-b3dee580-7b58-11eb-8d9e-18c1daf269c3.mp4

**Comment by Ifera** [comment]
> @xxAROX Yeah, I understand your approach in fixing this issue. I'd like to know if this bug occurs outside of InvMenu (i.e., it's a bug within the core).
> I would appreciate it if you could test if this bug occurs if you placed a chest on ground, opened it and moved an item from it while having a plugin cancel InventoryTransactionEvent.

@Muqsit, last I tested (don't exactly remember when) the core was at fault. InvMenu works just fine given that the problem lies at core i.e. PM or Minecraft don't exactly know which one is to blame here. (Although leaning towards PM here)

**Comment by xxAROX** [comment]
ahh okay

**Comment by Muqsit** [comment]
I suppose a plugin would be better than a virion in fixing this issue in that case, as events in virions are register by each plugin (i.e., two plugins using InvMenu would register the "fixed" InventoryTransactionEvent two times — one time by each plugin). As this issue is isolated from InvMenu, a plugin-fix would also fix any similar plugin or virion code that cancels InventoryTransactionEvent.
However, I'd suggest reporting it to PocketMine directly if you think it is a core issue.

**Pull request closed without merging**
