### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by zOmArRD**

### CODE REVIEW

**Comment by zOmArRD** [comment]
And Submit the Project please.

Link: [PACKAGIST](https://packagist.org/packages/submit)

**Comment by Muqsit** [comment]
Why would you like InvMenu to support composer may I ask?

**Comment by zOmArRD** [comment]
Sure, I don't want to use Virion, and I'm creating several plugins, and I prefer to use composer, if it's not a bother of course

**Comment by Muqsit** [comment]
Hello! This has been addressed in commits 392ebc5e5b36e849fdfe475222d106cf8cb3265c, https://github.com/Muqsit/InvMenu/commit/905244225e9a0d7962eb622a045b6eedf5bc6a67 😇

**Pull request closed without merging**
