### PR TITLE
InvMenu v3.0 targeting API 3

### PR DESCRIPTION
**Pull request by Muqsit**
## Introduction
InvMenu v3.0 consists of fixes to several unbearably annoying bugs in v2.0. Until now, that version only supported API 4.0. Since API 4.0's release is [an undefined period of time] away, I thought of porting it over to API 3.0.

## Changelog
https://github.com/Muqsit/InvMenu/wiki/InvMenu-v3.0

## Tests
Test plugin: https://gist.github.com/Muqsit/e131575670dfba7f36d42c9aabd8a5a9

## Fixes
- #41 
- #53 

Related to the issues mentioned above:
- Fixes a bug causing player's HUD to disappear when sending a menu right after another.

Awaiting some more tests.

### CODE REVIEW

**Comment by Adam1609** [comment]
Have been trying with ChestShop, HUD still disappeared

**Comment by Muqsit** [comment]
@Adam1609 this is a pull request, it hasn't been merged into release.

**Comment by Adam1609** [comment]
yeah i know. I am testing for you though xD

**Comment by Muqsit** [comment]
It fixes the issue with HUDs disappearing. You can test the test plugin and run InvMenu (branch master-3.0) from source.
As a matter of fact, I've already tested this with all my plugins that currently use it and it has worked fine.

**Comment by Adam1609** [comment]
It worked! Thanks to this I can easily manage the menu!

**Pull request merged**
